services:
  - type: web
    name: nexus-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nexus-db
          property: connectionString
      - key: JWT_SECRET
        value: your-secret-key

databases:
  - name: nexus-db
    plan: free
